// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/m11ano/avito-shop/internal/domain"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/m11ano/avito-shop/internal/usecase"

	uuid "github.com/google/uuid"
)

// CoinTransferRepository is an autogenerated mock type for the CoinTransferRepository type
type CoinTransferRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, coinTransfer
func (_m *CoinTransferRepository) Create(ctx context.Context, coinTransfer *domain.CoinTransfer) error {
	ret := _m.Called(ctx, coinTransfer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CoinTransfer) error); ok {
		r0 = rf(ctx, coinTransfer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindIdentity provides a mock function with given fields: ctx, identityKey
func (_m *CoinTransferRepository) FindIdentity(ctx context.Context, identityKey uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, identityKey)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentity")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, identityKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, identityKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, identityKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAggrCoinHistoryByAccountID provides a mock function with given fields: ctx, accountID, transferType
func (_m *CoinTransferRepository) GetAggrCoinHistoryByAccountID(ctx context.Context, accountID uuid.UUID, transferType domain.CoinTransferType) ([]usecase.CoinTransferRepositoryAggrHistoryItem, error) {
	ret := _m.Called(ctx, accountID, transferType)

	if len(ret) == 0 {
		panic("no return value specified for GetAggrCoinHistoryByAccountID")
	}

	var r0 []usecase.CoinTransferRepositoryAggrHistoryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.CoinTransferType) ([]usecase.CoinTransferRepositoryAggrHistoryItem, error)); ok {
		return rf(ctx, accountID, transferType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.CoinTransferType) []usecase.CoinTransferRepositoryAggrHistoryItem); ok {
		r0 = rf(ctx, accountID, transferType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecase.CoinTransferRepositoryAggrHistoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.CoinTransferType) error); ok {
		r1 = rf(ctx, accountID, transferType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCoinTransferRepository creates a new instance of CoinTransferRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoinTransferRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoinTransferRepository {
	mock := &CoinTransferRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
