run:
    timeout: 5m
    issues-exit-code: 1
    tests: true

issues:
    exclude-dirs:
        - "vendor"
        - "third_party"
        - "mocks"

linters:
    enable:
        - govet # Встроенный анализатор Go (аналог `go vet`)
        - gofmt # Проверка форматирования (аналог `go fmt -l`)
        - staticcheck # Улучшенный статический анализатор
        - errcheck # Проверяет, обработаны ли ошибки
        - unused # Ищет неиспользуемые переменные, функции, константы
        - ineffassign # Находит ненужные присваивания переменным
        - typecheck # Проверяет правильность типов
        - gofumpt # Улучшенный `gofmt`, форматирует Go-код по лучшим практикам
        - revive # Улучшенный линтер на замену устаревшему `golint`

linters-settings:
    errcheck:
        check-type-assertions: true
        check-blank: true

    staticcheck:
        checks: ["all"]

output:
    formats:
        - format: tab # Упрощённый формат вывода для терминала
