app:
    is_prod: true
    start_timeout: 60
    stop_timeout: 10
    use_logger: true

db:
    uri: "postgres://postgres:123456@localhost:5433/avito-shop"
    max_attempts: 10
    attempt_sleep_seconds: 3
    migrations_path: "migrations"

http:
    prefix: "api"
    port: 8080
    stop_timeout: 5
    under_proxy: false

auth:
    jwt_secret_key: "T9vq75NyopB05w2iO8Hp4iduv9xHD5woYWgfEDZmpKOOd4CDC8"
    jwt_token_ttl: 86400
    new_account_amount: 1000
